apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: budgetproperty
  labels:
    app: backend
type: Opaque
stringData:
  DB_USER: "santhira"
  DB_PASSWORD: "Santhira#%$2026"
  JWT_SECRET: "3251e1a406a238669039237a9ce90d88b3d3fc0ef592137b77066acef0bee637"
  MINIO_ACCESS_KEY: "minioadmin"
  MINIO_SECRET_KEY: "MinIO@saas2024"
  RAZORPAY_KEY_ID: "CHANGE_ME"
  RAZORPAY_KEY_SECRET: "CHANGE_ME"
  DVHOSTING_API_URL: "CHANGE_ME"
  DVHOSTING_API_KEY: "CHANGE_ME"
