#!/usr/bin/env bash
# ============================================================
# PHASE 1 — STEP 4: Site-to-Site VPN (AWS ↔ On-Prem FortiGate)
#
# STATUS: PENDING — Coordinate with Network Team first
#
# WHAT NETWORK TEAM NEEDS TO PROVIDE:
#   1. FortiGate public IP address (FORTIGATE_PUBLIC_IP)
#   2. On-prem BGP ASN (default: 65000)
#   3. On-prem LAN CIDR that needs to reach AWS (ONPREM_CIDR)
#   4. Preferred IKEv2 PSK or certificate auth
#
# WHAT YOU PROVIDE TO NETWORK TEAM (after running this script):
#   - AWS VPN endpoint IPs (2 tunnels for HA)
#   - Tunnel inside CIDRs
#   - Pre-shared keys (auto-generated by AWS)
#   - FortiGate config XML (downloaded automatically)
#
# NETWORK TEAM CHECKLIST:
#   [ ] Provide FortiGate public static IP
#   [ ] Confirm on-prem LAN range (currently assumed: 10.15.0.0/24)
#   [ ] Configure FortiGate with the downloaded XML config
#   [ ] Open outbound: UDP 500, UDP 4500 (IKE/NAT-T) to AWS VPN IPs
#   [ ] Verify tunnel status goes UP (both tunnels)
#   [ ] Test ping from on-prem → AWS private subnet
#
# RUN THIS SCRIPT only after network team provides FortiGate IP:
#   1. Edit .env.shared: set FORTIGATE_PUBLIC_IP="x.x.x.x"
#   2. Run: bash 01-network/04-create-vpn.sh
# ============================================================

source "$(dirname "$0")/../.env.shared"
source /tmp/le-network-ids.env

if [[ "${FORTIGATE_PUBLIC_IP}" == "<YOUR_FORTIGATE_PUBLIC_IP>" ]]; then
  echo ""
  echo "  ╔══════════════════════════════════════════════════════════╗"
  echo "  ║  VPN SETUP — PENDING NETWORK TEAM INPUT                 ║"
  echo "  ║                                                          ║"
  echo "  ║  Ask network team for:                                   ║"
  echo "  ║    1. FortiGate public IP                                ║"
  echo "  ║    2. On-prem LAN CIDR                                   ║"
  echo "  ║    3. BGP ASN (if using dynamic routing)                 ║"
  echo "  ║                                                          ║"
  echo "  ║  Then: edit .env.shared → set FORTIGATE_PUBLIC_IP       ║"
  echo "  ║  And re-run this script                                  ║"
  echo "  ╚══════════════════════════════════════════════════════════╝"
  echo ""
  echo "  Skipping VPN setup. All other infrastructure will work fine."
  echo "  On-prem connectivity can be added later without any downtime."
  exit 0
fi

set -euo pipefail

echo "============================================================"
echo " Site-to-Site VPN Setup (AWS ↔ FortiGate ${FORTIGATE_PUBLIC_IP})"
echo "============================================================"

# ─── VIRTUAL PRIVATE GATEWAY ─────────────────────────────────
echo "[4.1] Creating Virtual Private Gateway"
VGW_ID=$(aws ec2 create-vpn-gateway \
  --type ipsec.1 \
  --amazon-side-asn "${AWS_BGP_ASN}" \
  --tag-specifications "ResourceType=vpn-gateway,Tags=[
    {Key=Name,Value=${PROJECT}-vgw},{Key=Project,Value=${TAG_PROJECT}}
  ]" --query 'VpnGateway.VpnGatewayId' --output text)

aws ec2 attach-vpn-gateway --vpn-gateway-id "${VGW_ID}" --vpc-id "${VPC_ID}"
echo "    VGW ${VGW_ID} attached to VPC"

# ─── CUSTOMER GATEWAY ────────────────────────────────────────
echo "[4.2] Creating Customer Gateway (FortiGate)"
CGW_ID=$(aws ec2 create-customer-gateway \
  --type ipsec.1 \
  --public-ip "${FORTIGATE_PUBLIC_IP}" \
  --bgp-asn "${ONPREM_BGP_ASN}" \
  --tag-specifications "ResourceType=customer-gateway,Tags=[
    {Key=Name,Value=${PROJECT}-cgw-fortigate},{Key=Project,Value=${TAG_PROJECT}}
  ]" --query 'CustomerGateway.CustomerGatewayId' --output text)

# ─── VPN CONNECTION ──────────────────────────────────────────
echo "[4.3] Creating VPN Connection (IKEv2, AES-256-GCM)"
VPN_ID=$(aws ec2 create-vpn-connection \
  --type ipsec.1 \
  --customer-gateway-id "${CGW_ID}" \
  --vpn-gateway-id "${VGW_ID}" \
  --options '{
    "StaticRoutesOnly": false,
    "TunnelOptions": [
      {"IKEVersions": [{"Value": "ikev2"}],
       "Phase1EncryptionAlgorithms": [{"Value": "AES256GCM16"}],
       "Phase2EncryptionAlgorithms": [{"Value": "AES256GCM16"}]},
      {"IKEVersions": [{"Value": "ikev2"}],
       "Phase1EncryptionAlgorithms": [{"Value": "AES256GCM16"}],
       "Phase2EncryptionAlgorithms": [{"Value": "AES256GCM16"}]}
    ]
  }' \
  --tag-specifications "ResourceType=vpn-connection,Tags=[
    {Key=Name,Value=${PROJECT}-vpn-onprem},{Key=Project,Value=${TAG_PROJECT}}
  ]" --query 'VpnConnection.VpnConnectionId' --output text)

aws ec2 create-vpn-connection-route \
  --destination-cidr-block "${ONPREM_CIDR}" \
  --vpn-connection-id "${VPN_ID}"

aws ec2 enable-vgw-route-propagation --route-table-id "${PRIV_RTB_AZ1}" --gateway-id "${VGW_ID}"

# Download FortiGate config
aws ec2 describe-vpn-connections --vpn-connection-ids "${VPN_ID}" \
  --query 'VpnConnections[0].CustomerGatewayConfiguration' --output text \
  > /tmp/fortigate-vpn-config.xml

cat >> /tmp/le-network-ids.env <<EOF
export VGW_ID="${VGW_ID}"
export CGW_ID="${CGW_ID}"
export VPN_ID="${VPN_ID}"
EOF

echo ""
echo "[DONE] VPN Connection created: ${VPN_ID}"
echo "  Send /tmp/fortigate-vpn-config.xml to network team"
echo "  Check tunnel status: aws ec2 describe-vpn-connections --vpn-connection-ids ${VPN_ID}"
