"""
NginxNexus MCP Server — Reverse Proxy & Load Balancer Intelligence
===================================================================
AI-native Nginx management: config generation, upstream management,
SSL/TLS automation, rate limiting, caching, and health monitoring.
Uses Nginx Plus API or config file management via subprocess.

Author: Santhira (Rajkumar Madhu) | Port: 8005
"""

from mcp.server.fastmcp import FastMCP
from pydantic import BaseModel, Field, ConfigDict
from typing import Optional, List, Dict, Any, Literal
from enum import Enum
import json, os, subprocess, tempfile

mcp = FastMCP("nginx_nexus_mcp")

class ResponseFormat(str, Enum):
    MARKDOWN = "markdown"
    JSON = "json"

def _safe_json(data): return json.dumps(data, indent=2, default=str)
def _run_cmd(cmd): return subprocess.run(cmd, shell=True, capture_output=True, text=True, timeout=10)
def _handle_error(e): return f"Error: {type(e).__name__} — {str(e)}"

NGINX_CONF_DIR = os.environ.get("NGINX_CONF_DIR", "/etc/nginx")

# ---- INPUT MODELS ----

class NginxConfigGenInput(BaseModel):
    model_config = ConfigDict(str_strip_whitespace=True, extra="forbid")
    server_name: str = Field(..., description="Domain name (e.g., 'api.santhira.com')")
    upstream_servers: List[str] = Field(..., description="Backend servers (e.g., ['10.0.1.1:8000', '10.0.1.2:8000'])")
    listen_port: int = Field(default=443, ge=80, le=65535)
    ssl: bool = Field(default=True, description="Enable HTTPS")
    ssl_cert_path: Optional[str] = Field(default=None, description="SSL certificate path")
    ssl_key_path: Optional[str] = Field(default=None, description="SSL key path")
    load_balance: Literal["round_robin", "least_conn", "ip_hash", "random"] = Field(default="round_robin")
    rate_limit: Optional[str] = Field(default=None, description="Rate limit (e.g., '100r/s', '10r/m')")
    cache_enabled: bool = Field(default=False, description="Enable proxy caching")
    websocket: bool = Field(default=False, description="Enable WebSocket support")
    health_check_path: Optional[str] = Field(default=None, description="Backend health check path (e.g., '/health')")
    max_body_size: str = Field(default="10m", description="Client max body size")
    custom_headers: Optional[Dict[str, str]] = Field(default=None)
    gzip: bool = Field(default=True, description="Enable gzip compression")

class NginxTestInput(BaseModel):
    model_config = ConfigDict(str_strip_whitespace=True, extra="forbid")
    config_content: Optional[str] = Field(default=None, description="Config content to test (or test existing)")

class NginxStatusInput(BaseModel):
    model_config = ConfigDict(str_strip_whitespace=True, extra="forbid")
    response_format: ResponseFormat = Field(default=ResponseFormat.MARKDOWN)

class NginxSSLInput(BaseModel):
    model_config = ConfigDict(str_strip_whitespace=True, extra="forbid")
    domain: str = Field(..., description="Domain for SSL certificate")
    action: Literal["generate_self_signed", "certbot_command", "check_expiry"] = Field(...)

class NginxSecurityInput(BaseModel):
    model_config = ConfigDict(str_strip_whitespace=True, extra="forbid")
    server_name: str = Field(..., description="Domain to generate security headers for")
    level: Literal["basic", "strict", "paranoid"] = Field(default="strict")

class NginxUpstreamAdvisorInput(BaseModel):
    model_config = ConfigDict(str_strip_whitespace=True, extra="forbid")
    use_case: str = Field(..., description="Describe your application and traffic pattern")
    backend_count: int = Field(default=3, ge=1, le=100)
    expected_rps: Optional[int] = Field(default=None, description="Expected requests per second")
    response_format: ResponseFormat = Field(default=ResponseFormat.MARKDOWN)

class NginxHealthInput(BaseModel):
    model_config = ConfigDict(str_strip_whitespace=True, extra="forbid")
    response_format: ResponseFormat = Field(default=ResponseFormat.MARKDOWN)

# ---- TOOLS ----

@mcp.tool(name="nginx_config_generate", annotations={"title": "Generate Nginx Config", "readOnlyHint": True, "destructiveHint": False, "idempotentHint": True, "openWorldHint": False})
async def nginx_config_generate(params: NginxConfigGenInput, ctx=None) -> str:
    """Generate production-ready Nginx configuration with load balancing, SSL, rate limiting,
    caching, WebSocket support, security headers, and gzip compression.
    Returns: Complete nginx server block configuration.
    """
    lb_method = {"round_robin": "", "least_conn": "    least_conn;", "ip_hash": "    ip_hash;", "random": "    random two least_conn;"}
    upstream_name = params.server_name.replace(".", "_")

    config = f"# Generated by NginxNexus MCP — {params.server_name}\n"
    config += f"# Load Balance: {params.load_balance} | SSL: {params.ssl} | Cache: {params.cache_enabled}\n\n"

    # Rate limiting zone
    if params.rate_limit:
        config += f"limit_req_zone $binary_remote_addr zone=api_{upstream_name}:10m rate={params.rate_limit};\n\n"

    # Cache path
    if params.cache_enabled:
        config += f"proxy_cache_path /var/cache/nginx/{upstream_name} levels=1:2 keys_zone={upstream_name}_cache:10m max_size=1g inactive=60m;\n\n"

    # Upstream block
    config += f"upstream {upstream_name} {{\n"
    if lb_method[params.load_balance]:
        config += f"{lb_method[params.load_balance]}\n"
    config += "    keepalive 32;\n"
    for server in params.upstream_servers:
        config += f"    server {server} max_fails=3 fail_timeout=30s;\n"
    config += "}\n\n"

    # HTTP → HTTPS redirect
    if params.ssl:
        config += f"server {{\n    listen 80;\n    server_name {params.server_name};\n    return 301 https://$host$request_uri;\n}}\n\n"

    # Main server block
    config += f"server {{\n"
    if params.ssl:
        config += f"    listen {params.listen_port} ssl http2;\n"
        cert = params.ssl_cert_path or f"/etc/letsencrypt/live/{params.server_name}/fullchain.pem"
        key = params.ssl_key_path or f"/etc/letsencrypt/live/{params.server_name}/privkey.pem"
        config += f"    ssl_certificate {cert};\n"
        config += f"    ssl_certificate_key {key};\n"
        config += "    ssl_protocols TLSv1.2 TLSv1.3;\n"
        config += "    ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384;\n"
        config += "    ssl_prefer_server_ciphers off;\n"
        config += "    ssl_session_cache shared:SSL:10m;\n"
        config += "    ssl_session_timeout 1d;\n"
        config += "    ssl_stapling on;\n    ssl_stapling_verify on;\n\n"
    else:
        config += f"    listen {params.listen_port};\n"

    config += f"    server_name {params.server_name};\n"
    config += f"    client_max_body_size {params.max_body_size};\n\n"

    # Security headers
    config += "    # Security Headers\n"
    config += "    add_header X-Frame-Options DENY always;\n"
    config += "    add_header X-Content-Type-Options nosniff always;\n"
    config += "    add_header X-XSS-Protection \"1; mode=block\" always;\n"
    config += "    add_header Referrer-Policy strict-origin-when-cross-origin always;\n"
    if params.ssl:
        config += "    add_header Strict-Transport-Security \"max-age=63072000; includeSubDomains; preload\" always;\n"

    if params.custom_headers:
        for k, v in params.custom_headers.items():
            config += f"    add_header {k} \"{v}\" always;\n"
    config += "\n"

    # Gzip
    if params.gzip:
        config += "    # Compression\n"
        config += "    gzip on;\n    gzip_vary on;\n    gzip_min_length 1024;\n"
        config += "    gzip_types text/plain application/json application/javascript text/css application/xml;\n\n"

    # Logging
    config += f"    access_log /var/log/nginx/{upstream_name}_access.log;\n"
    config += f"    error_log /var/log/nginx/{upstream_name}_error.log warn;\n\n"

    # Main location
    config += "    location / {\n"
    if params.rate_limit:
        config += f"        limit_req zone=api_{upstream_name} burst=20 nodelay;\n"
    if params.cache_enabled:
        config += f"        proxy_cache {upstream_name}_cache;\n"
        config += "        proxy_cache_valid 200 302 10m;\n"
        config += "        proxy_cache_valid 404 1m;\n"
        config += "        add_header X-Cache-Status $upstream_cache_status;\n"
    config += f"        proxy_pass http://{upstream_name};\n"
    config += "        proxy_set_header Host $host;\n"
    config += "        proxy_set_header X-Real-IP $remote_addr;\n"
    config += "        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;\n"
    config += "        proxy_set_header X-Forwarded-Proto $scheme;\n"
    config += "        proxy_http_version 1.1;\n"
    config += "        proxy_set_header Connection \"\";\n"

    if params.websocket:
        config += "\n        # WebSocket\n"
        config += "        proxy_set_header Upgrade $http_upgrade;\n"
        config += "        proxy_set_header Connection \"upgrade\";\n"
        config += "        proxy_read_timeout 86400;\n"

    config += "        proxy_connect_timeout 5s;\n"
    config += "        proxy_read_timeout 60s;\n"
    config += "        proxy_send_timeout 60s;\n"
    config += "    }\n"

    # Health check endpoint
    if params.health_check_path:
        config += f"\n    location {params.health_check_path} {{\n"
        config += f"        proxy_pass http://{upstream_name};\n"
        config += "        access_log off;\n"
        config += "    }\n"

    # Static files
    config += "\n    # Static files (optional)\n"
    config += "    location ~* \\.(js|css|png|jpg|jpeg|gif|ico|svg|woff2)$ {\n"
    config += "        expires 30d;\n        add_header Cache-Control \"public, immutable\";\n"
    config += f"        proxy_pass http://{upstream_name};\n"
    config += "    }\n"

    config += "}\n"

    return f"## 🔧 Generated Nginx Config for `{params.server_name}`\n\n```nginx\n{config}\n```\n\n💡 Save to: `{NGINX_CONF_DIR}/sites-available/{upstream_name}.conf`"

@mcp.tool(name="nginx_test_config", annotations={"title": "Test Config", "readOnlyHint": True, "destructiveHint": False, "idempotentHint": True, "openWorldHint": False})
async def nginx_test_config(params: NginxTestInput, ctx=None) -> str:
    """Test Nginx configuration syntax without applying."""
    try:
        if params.config_content:
            with tempfile.NamedTemporaryFile(mode='w', suffix='.conf', delete=False) as f:
                f.write(params.config_content)
                f.flush()
                result = _run_cmd(f"nginx -t -c {f.name}")
                os.unlink(f.name)
        else:
            result = _run_cmd("nginx -t")
        output = result.stderr or result.stdout
        if result.returncode == 0:
            return f"✅ Nginx configuration test passed!\n```\n{output}\n```"
        return f"❌ Configuration test FAILED:\n```\n{output}\n```"
    except Exception as e:
        return _handle_error(e)

@mcp.tool(name="nginx_status", annotations={"title": "Server Status", "readOnlyHint": True, "destructiveHint": False, "idempotentHint": True, "openWorldHint": False})
async def nginx_status(params: NginxStatusInput, ctx=None) -> str:
    """Get Nginx server status: process info, connections, version."""
    try:
        version = _run_cmd("nginx -v")
        ps = _run_cmd("ps aux | grep nginx | grep -v grep")
        connections = _run_cmd("ss -tlnp | grep nginx")

        md = "## 🌐 Nginx Status\n\n"
        md += f"**Version:** {(version.stderr or version.stdout).strip()}\n\n"
        md += f"### Processes\n```\n{ps.stdout}\n```\n"
        md += f"### Listening\n```\n{connections.stdout or 'No listeners found'}\n```"
        return md
    except Exception as e:
        return _handle_error(e)

@mcp.tool(name="nginx_ssl_manage", annotations={"title": "SSL Manager", "readOnlyHint": True, "destructiveHint": False, "idempotentHint": True, "openWorldHint": False})
async def nginx_ssl_manage(params: NginxSSLInput, ctx=None) -> str:
    """SSL certificate management: generate self-signed, certbot commands, check expiry."""
    try:
        if params.action == "generate_self_signed":
            cmd = f"openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/ssl/{params.domain}.key -out /etc/ssl/{params.domain}.crt -subj '/CN={params.domain}'"
            return f"## 🔐 Self-Signed SSL for `{params.domain}`\n\n```bash\n{cmd}\n```\n\n⚠️ Self-signed certs show browser warnings. Use Let's Encrypt for production."

        elif params.action == "certbot_command":
            return f"## 🔐 Let's Encrypt SSL for `{params.domain}`\n\n```bash\n# Install certbot\napt install certbot python3-certbot-nginx -y\n\n# Get certificate\ncertbot --nginx -d {params.domain} --non-interactive --agree-tos -m admin@{params.domain}\n\n# Auto-renew\ncertbot renew --dry-run\n```"

        elif params.action == "check_expiry":
            result = _run_cmd(f"echo | openssl s_client -connect {params.domain}:443 -servername {params.domain} 2>/dev/null | openssl x509 -noout -dates")
            return f"## 🔐 SSL Certificate: `{params.domain}`\n```\n{result.stdout or 'Could not connect'}\n```"
    except Exception as e:
        return _handle_error(e)

@mcp.tool(name="nginx_security_headers", annotations={"title": "Security Headers Generator", "readOnlyHint": True, "destructiveHint": False, "idempotentHint": True, "openWorldHint": False})
async def nginx_security_headers(params: NginxSecurityInput, ctx=None) -> str:
    """Generate security headers configuration for Nginx based on security level."""
    headers = {
        "basic": [
            'add_header X-Frame-Options "SAMEORIGIN" always;',
            'add_header X-Content-Type-Options "nosniff" always;',
            'add_header X-XSS-Protection "1; mode=block" always;',
        ],
        "strict": [
            'add_header X-Frame-Options "DENY" always;',
            'add_header X-Content-Type-Options "nosniff" always;',
            'add_header X-XSS-Protection "1; mode=block" always;',
            'add_header Referrer-Policy "strict-origin-when-cross-origin" always;',
            'add_header Strict-Transport-Security "max-age=63072000; includeSubDomains; preload" always;',
            'add_header Permissions-Policy "camera=(), microphone=(), geolocation=()" always;',
        ],
        "paranoid": [
            'add_header X-Frame-Options "DENY" always;',
            'add_header X-Content-Type-Options "nosniff" always;',
            'add_header X-XSS-Protection "1; mode=block" always;',
            'add_header Referrer-Policy "no-referrer" always;',
            'add_header Strict-Transport-Security "max-age=63072000; includeSubDomains; preload" always;',
            'add_header Permissions-Policy "camera=(), microphone=(), geolocation=(), payment=()" always;',
            f'add_header Content-Security-Policy "default-src \'self\'; script-src \'self\'; style-src \'self\' \'unsafe-inline\'; img-src \'self\' data:; font-src \'self\';" always;',
            'add_header Cross-Origin-Opener-Policy "same-origin" always;',
            'add_header Cross-Origin-Resource-Policy "same-origin" always;',
        ],
    }
    config = "\n".join(headers[params.level])
    return f"## 🛡️ Security Headers — `{params.level}` level for `{params.server_name}`\n\n```nginx\n# Add inside server block\n{config}\n```"

@mcp.tool(name="nginx_upstream_advisor", annotations={"title": "AI Upstream Advisor", "readOnlyHint": True, "destructiveHint": False, "idempotentHint": True, "openWorldHint": False})
async def nginx_upstream_advisor(params: NginxUpstreamAdvisorInput, ctx=None) -> str:
    """AI-powered load balancing and upstream strategy advisor."""
    use = params.use_case.lower()

    if any(w in use for w in ["api", "rest", "microservice"]):
        strategy = "least_conn"
        notes = ["Use least_conn for API backends with varying response times", "Set keepalive 32 for connection reuse", "Set max_fails=3 fail_timeout=30s for circuit breaking"]
    elif any(w in use for w in ["websocket", "real-time", "socket", "chat"]):
        strategy = "ip_hash"
        notes = ["Use ip_hash for sticky sessions (WebSocket requires same backend)", "Set proxy_read_timeout 86400 for long connections", "Enable Upgrade and Connection headers"]
    elif any(w in use for w in ["static", "cdn", "assets", "file"]):
        strategy = "round_robin"
        notes = ["Round robin for stateless static file serving", "Enable proxy_cache for aggressive caching", "Set expires 30d for immutable assets"]
    elif any(w in use for w in ["trading", "finance", "low-latency"]):
        strategy = "least_conn"
        notes = ["least_conn for lowest latency distribution", "Increase worker_connections to 4096+", "Disable access logging for performance", "Use keepalive 64 for warm connections"]
    else:
        strategy = "round_robin"
        notes = ["Default round_robin works for most balanced workloads", "Monitor backend response times and switch to least_conn if uneven"]

    md = f"## 🧠 Upstream Strategy: {strategy}\n\n"
    md += f"**Use Case:** {params.use_case}\n**Backends:** {params.backend_count}\n"
    if params.expected_rps:
        md += f"**Expected RPS:** {params.expected_rps}\n"
    md += "\n### Recommendations\n"
    for n in notes:
        md += f"- {n}\n"
    return md

@mcp.tool(name="nginx_health_check", annotations={"title": "AI Health Check", "readOnlyHint": True, "destructiveHint": False, "idempotentHint": True, "openWorldHint": False})
async def nginx_health_check(params: NginxHealthInput, ctx=None) -> str:
    """Comprehensive Nginx health check: process status, config validity, SSL, error logs."""
    try:
        issues, score = [], 100

        # Process running?
        ps = _run_cmd("pgrep -c nginx")
        if ps.returncode != 0:
            issues.append(("🔴", "Nginx is NOT running!"))
            score -= 40

        # Config valid?
        test = _run_cmd("nginx -t 2>&1")
        if test.returncode != 0:
            issues.append(("🔴", "Nginx config has syntax errors"))
            score -= 20

        # Error log recent errors
        errors = _run_cmd("tail -20 /var/log/nginx/error.log 2>/dev/null | grep -c 'error\\|crit\\|emerg'")
        err_count = int(errors.stdout.strip()) if errors.stdout.strip().isdigit() else 0
        if err_count > 5:
            issues.append(("🟡", f"{err_count} recent errors in error log"))
            score -= 10

        score = max(0, score)
        emoji = "🟢" if score >= 80 else "🟡" if score >= 50 else "🔴"
        md = f"## {emoji} Nginx Health — Score: {score}/100\n\n"
        if issues:
            md += "### Issues\n" + "".join(f"- {s} {m}\n" for s, m in issues)
        else:
            md += "✅ Nginx is healthy!\n"
        return md
    except Exception as e:
        return _handle_error(e)

if __name__ == "__main__":
    import sys
    transport = "stdio"
    for arg in sys.argv[1:]:
        if arg == "--http": transport = "streamable_http"
    mcp.run(transport=transport, port=8005) if transport == "streamable_http" else mcp.run()
